### ISSUE TITLE
[DEV]: Time Temperature - Biome Class Support

### ISSUE THREAD

**Issue by northwesttreesgaming** [northwesttrees-gaming/ThermalAPI#12]
# About
Make an optional setting to allow biome classes the ability to work independently for time temperature.
## Tasks
- [ ] Create a dynamic biome class system.
- [ ] Add "ttb_[class_name].json" file.
- [ ] Add custom file support.
